In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
#csv file, we will use the property data.csv file
data = pd.read_csv("propertyData.csv")
print(data)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [4]:
#Viewing the first 5 rows
data.head()

           PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
2  100003000.0     NaN  LEXINGTON            N          NaN        1   850
3  100004000.0   201.0   BERKELEY           12            1      NaN   700
4          NaN   203.0   BERKELEY            Y            3        2  1600

In [5]:
#viewing the last 5 rows
data.tail()

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [7]:
#Dataset shape
data.shape

(9, 7)

In [8]:
#Dataset basic analysis
print(data.describe())

                PID      ST_NUM
count  8.000000e+00    7.000000
mean   1.000050e+08  191.428571
std    2.927700e+03   39.080503
min    1.000010e+08  104.000000
25%    1.000028e+08  199.000000
50%    1.000050e+08  203.000000
75%    1.000072e+08  210.000000
max    1.000090e+08  215.000000

* Note that Pandas library only recognizes NaN as the missing value. It skips other missing values, e.g. na, NULL and N/A. See the following solution to address this issue.

In [24]:
# You can define a list to represent all missing values
missing_values = ["n/a", "na", "--"] 
df = pd.read_csv("propertyData.csv", na_values = missing_values)

In [25]:
# check data and df differences to see how na and -- became NaN
print(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [11]:
print(df['NUM_BEDROOMS'])

0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    1.0
8    NaN
Name: NUM_BEDROOMS, dtype: float64

In [12]:
print(df['NUM_BEDROOMS'].isnull())

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
Name: NUM_BEDROOMS, dtype: bool

In [15]:
print(df['OWN_OCCUPIED'])

0      Y
1      N
2      N
3     12
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: OWN_OCCUPIED, dtype: object

In [16]:
# Looking at the OWN_OCCUPIED column
print(df['OWN_OCCUPIED'].isnull())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
Name: OWN_OCCUPIED, dtype: bool

In [14]:
#Showing total number of NaN values
df.isnull().sum()

PID             1
ST_NUM          2
ST_NAME         0
OWN_OCCUPIED    1
NUM_BEDROOMS    3
NUM_BATH        1
SQ_FT           2
dtype: int64

In [15]:
#Return true if any NaN values
df.isnull().any()

PID              True
ST_NUM           True
ST_NAME         False
OWN_OCCUPIED     True
NUM_BEDROOMS     True
NUM_BATH         True
SQ_FT            True
dtype: bool

In [13]:
#Total number of missing values - all table
df.isnull().sum().sum()

10

In [14]:
# Replace missing values with any number
df['ST_NUM'].fillna(111, inplace=True)

In [15]:
print(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   111.0   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0   111.0  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [17]:
# Location based replacement - 4th row in ST_NUM column
df.loc[4,'ST_NUM'] = 125

In [18]:
print(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   111.0   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   125.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0   111.0  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [19]:
# Replace using median value 
median = df['NUM_BEDROOMS'].median()
df['NUM_BEDROOMS'].fillna(median, inplace=True)

In [23]:
print(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   111.0   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   125.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0   111.0  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0

In [21]:
# If you want to drop "any" rows that contain NaN
# If you set "how" to "all", then the row is dropped only when all values are NaN
# Axis=0 is for dropping rows, Axis=1 is for dropping columns that contain NaN
df=df.dropna(axis=0, how='any')
print(df)

           PID  ST_NUM    ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0     PUTNAM            Y           3.0        1  1000.0
2  100003000.0   111.0  LEXINGTON            N           2.5        1   850.0
5  100006000.0   207.0   BERKELEY            Y           2.5        1   800.0
8  100009000.0   215.0    TREMONT            Y           2.5        2  1800.0

In [ ]:
#Replace all Nan values with 1212, by default returns a copy of the dataFrame as inplace is set to False.
df.fillna(1212)
#Replace all NaN values with forward fill, with the values above it.
df.ffill()
#Replace all Nan values with backward fill, with the values below it.
df.bfill()
#Replace all values with interpolation, average below and above values only if they are additive.
# You can check datatypes with "df.dtypes" and see why NaN values were not interpolated.
df.interpolate()
df.dtypes

In [26]:
# lets observe the datatypes for categorical features using df.dtypes
df.dtypes
# We know that there is a NaN value in OWN_OCCUPIED column
from sklearn.impute import SimpleImputer
import pandas as pdx
imputer = SimpleImputer(strategy='most_frequent')
dataarray=imputer.fit_transform(df['OWN_OCCUPIED'].to_numpy().reshape(-1, 1))
#dfconvert=pdx.DataFrame(dataarray,columns=['PID',	'ST_NUM',	'ST_NAME',	'OWN_OCCUPIED',	'NUM_BEDROOMS',	'NUM_BATH',	'SQ_FT'])
dfconvert=pdx.DataFrame(dataarray,columns=['OWN_OCCUPIED'])
print(dfconvert)
print(df)
# Missing value is imputed with 'Y'

  OWN_OCCUPIED
0            Y
1            N
2            N
3           12
4            Y
5            Y
6            Y
7            Y
8            Y
           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [28]:
#Imputing missing values using Sci-kit library
#SimpleImputer can be used for Univariate approach considering a single feature.
#There are other methods, such as KNNImputer/IterativeImputer, which can be used for Multivariate and Nearest Neighbours Imputations.
from sklearn.impute import SimpleImputer
import pandas as pdy
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
idf=pdy.DataFrame(imp.fit_transform(df['SQ_FT'].to_numpy().reshape(-1,1)))
print(idf)
print(df)

        0
0  1000.0
1  1100.0
2   850.0
3   700.0
4  1600.0
5   800.0
6   950.0
7  1100.0
8  1800.0
           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [29]:
# Can you now integrate the idf data int df by replacing the SQ_FT column?
df['SQ_FT']=idf[0]
print(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5  1100.0
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1  1100.0
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [32]:
df3 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df4 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

result = pd.concat([df3,df4], axis=1, join="outer") # axis 1 refers to column, 0 refers to row # join=outer (union) by default and inner (intersection)
result

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [33]:
d2 = {'Name': ['Lily', 'Meghna', 'Lisa'], 'Country': ['UK', 'India', 'USA'], 'Role': ['CEO', 'CTO', 'CTO']}
df6 = pd.DataFrame(d2)
print('DataFrame 1:\n', df6)
df7 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Lily', 'Eric', 'Johanna']})
print('DataFrame 2:\n', df7)

df_merged = df6.merge(df7) #default merging - inner join
print('Result:\n', df_merged)

DataFrame 1:
      Name Country Role
0    Lily      UK  CEO
1  Meghna   India  CTO
2    Lisa     USA  CTO
DataFrame 2:
    ID     Name
0   1     Lily
1   2     Eric
2   3  Johanna
Result:
    Name Country Role  ID
0  Lily      UK  CEO   1

In [34]:
print('Result Left Join:\n', df6.merge(df7, how='left'))

Result Left Join:
      Name Country Role   ID
0    Lily      UK  CEO  1.0
1  Meghna   India  CTO  NaN
2    Lisa     USA  CTO  NaN

In [35]:
print('Result Right Join:\n', df6.merge(df7, how='right'))

Result Right Join:
       Name Country Role  ID
0     Lily      UK  CEO   1
1     Eric     NaN  NaN   2
2  Johanna     NaN  NaN   3

In [43]:
print('Result Outer Join:\n', df6.merge(df7, how='outer'))

Result Outer Join:
       Name Country Role   ID
0     Lily      UK  CEO  1.0
1   Meghna   India  CTO  NaN
2     Lisa     USA  CTO  NaN
3     Eric     NaN  NaN  2.0
4  Johanna     NaN  NaN  3.0